include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - prefer_const_constructors
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    - file_names

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"

  errors:
    invalid_annotation_target: ignore
    always_use_package_imports: error
    prefer_const_constructors: error
    use_is_even_rather_than_modulo: error
    use_named_constants: error
    use_build_context_synchronously: error
    use_key_in_widget_constructors: error
    file_names: error