name: gr_clothing_flutter
description: 激ロックFlutterアプリケーション iOS, Android対応

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  webview_flutter: ^3.0.4
  flutter_launcher_icons: ^0.9.2
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^12.0.2
  flutter_native_splash: ^2.2.11
  url_launcher: ^6.1.6
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.10
  flutter_gen_runner: ^4.1.6

flutter:
  uses-material-design: true

  fonts:
    - family: Hiragino
      fonts:
        - asset: assets/fonts/hiragino_kaku_gothic_1.ttc
          weight: 100
        - asset: assets/fonts/hiragino_kaku_gothic_2.ttc
          weight: 200
        - asset: assets/fonts/hiragino_kaku_gothic_3.ttc
          weight: 300
        - asset: assets/fonts/hiragino_kaku_gothic_4.ttc
          weight: 400
        - asset: assets/fonts/hiragino_kaku_gothic_5.ttc
          weight: 500
        - asset: assets/fonts/hiragino_kaku_gothic_6.ttc
          weight: 600
        - asset: assets/fonts/hiragino_kaku_gothic_7.ttc
          weight: 700
        - asset: assets/fonts/hiragino_kaku_gothic_8.ttc
          weight: 800
        - asset: assets/fonts/hiragino_kaku_gothic_9.ttc
          weight: 900

flutter_gen:
  colors:
    inputs:
      - assets/colors.xml

flutter_icons:
  android: "launcher_icon"
  ios: true
  background_color: '#3FBDE0'
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: '#3FBDE0'
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"

flutter_native_splash:
  color: "#3FBDE0"
  fullscreen: true
  image: assets/icon/splash_icon.png
  color_dark: "#3FBDE0"
  image_dark: assets/icon/splash_icon.png

  android_12:
    image: assets/icon/adaptive_icon.png
    icon_background_color: "#3FBDE0"
    image_dark: assets/icon/adaptive_icon.png
    icon_background_color_dark: "#3FBDE0"
